version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./uploads:/app/uploads
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 512M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.core.somaxconn=65536
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_fin_timeout=30